services:
  siffleux-server:
    image: siffleux-benchmark-test
    command: server
    networks:
      - siffleux-net
  siffleux-client:
    image: siffleux-benchmark-test
    command: udp-latency --server siffleux-server --mps 10000 -t 20
    environment:
      - RUST_LOG=INFO
    depends_on:
      - siffleux-server
    networks:
      - siffleux-net
networks:
  siffleux-net:
    driver: bridge
