[client]
remote_addr = "rathole-tls-server:2333"

[client.transport]
type = "tls"

[client.transport.tls]
trusted_root = "/app/certs/ca.pem"
hostname = "rathole"

[client.services.sockperf]
token = "secret!123"
local_addr = "siffleux-benchmark:11111"

[client.services.nginx]
token = "secret!123"
local_addr = "siffleux-benchmark:80"

[client.services.iperf3]
token = "secret!123"
local_addr = "siffleux-benchmark:5201"

[client.services.tcp_echo]
token = "secret!123"
local_addr = "siffleux-benchmark:3001"
