[client]
remote_addr = "rathole-tls-server:2333"

[client.transport]
type = "tls"

[client.transport.tls]
trusted_root = "/app/certs/ca.pem"
hostname = "rathole"

[client.services.siffle]
token = "secret!123"
local_addr = "tunnel-server:5678"

[client.services.nginx]
token = "secret!123"
local_addr = "tunnel-server:80"

[client.services.iperf3]
token = "secret!123"
local_addr = "tunnel-server:5201"

[client.services.tcp_echo]
token = "secret!123"
local_addr = "tunnel-server:3001"
