services:
  test-server:
    image: siffleux-benchmark:latest
    volumes:
      - ./tests:/tests
    command: server
  tunnel-server:
    image: siffleux-benchmark:latest
    volumes:
      - ./tests:/tests
    command: tunnel
  tunnel-client:
    image: siffleux-benchmark:latest
    volumes:
      - ./tests:/tests
    command: tunnel
  # siffleux-client:
  #   # image: ghcr.io/djxy/siffleux:latest
  #   image: siffleux
  #   volumes:
  #     - ./configs/siffleux/client.toml:/siffleux/config.toml
  #   command: client --config /siffleux/config.toml
  #   depends_on:
  #     - siffleux-server
  #   networks:
  #     - siffleux-net
  # siffleux-client-network:
  #   image: alpine
  #   cap_add:
  #     - NET_ADMIN
  #   network_mode: "service:siffleux-client"
  #   depends_on:
  #     - siffleux-client
  #   command: >
  #     sh -c "
  #       apk add --no-cache iproute2
  #       tc qdisc del dev eth0 root
  #       tc qdisc add dev eth0 root netem delay 10ms 5ms 25% distribution normal loss 1% 20% corrupt 0%
  #       # tc qdisc add dev eth0 root netem delay 10ms 5ms distribution normal
  #       tc qdisc show dev eth0
  #     "
