[server]
address = "siffleux-server:8765"
certificate_hash = "smVvwBEKwl0EHp_YonwvNClf1a6-LRLg0bficvKH_Qw="

[[tcp_egress]]
id = "sockperf-tcp"
ingress_id = "sockperf-tcp"
auth_key = "secret!123"
target = "siffleux-benchmark:11111"

[[udp_egress]]
id = "sockperf-udp"
ingress_id = "sockperf-udp"
auth_key = "secret!123"
target = "siffleux-benchmark:11111"

[[tcp_egress]]
id = "nginx"
ingress_id = "nginx"
auth_key = "secret!123"
target = "siffleux-benchmark:80"

[[tcp_egress]]
id = "echo-tcp"
ingress_id = "echo-tcp"
auth_key = "secret!123"
target = "siffleux-benchmark:3001"

[[udp_egress]]
id = "echo-udp"
ingress_id = "echo-udp"
auth_key = "secret!123"
target = "siffleux-benchmark:3001"

[[tcp_egress]]
id = "iperf3-tcp"
ingress_id = "iperf3-tcp"
auth_key = "secret!123"
target = "siffleux-benchmark:5201"

[[udp_egress]]
id = "iperf3-udp"
ingress_id = "iperf3-udp"
auth_key = "secret!123"
target = "siffleux-benchmark:5201"
