[server]
address = "tunnel-server:8765"
cert_hash = "J5xuXbO1jaSUcHeZ4DG0uYgCr9K1VpxNdwlmUUgxGVE="

[[tcp_egress]]
id = "siffle-tcp"
ingress_id = "siffle-tcp"
auth_key = "secret!123"
target = "test-server:5678"

[[udp_egress]]
id = "siffle-udp"
ingress_id = "siffle-udp"
auth_key = "secret!123"
target = "test-server:5678"

[[tcp_egress]]
id = "nginx"
ingress_id = "nginx"
auth_key = "secret!123"
target = "test-server:80"

[[tcp_egress]]
id = "echo-tcp"
ingress_id = "echo-tcp"
auth_key = "secret!123"
target = "test-server:3001"

[[udp_egress]]
id = "echo-udp"
ingress_id = "echo-udp"
auth_key = "secret!123"
target = "test-server:3001"

[[tcp_egress]]
id = "iperf3-tcp"
ingress_id = "iperf3-tcp"
auth_key = "secret!123"
target = "test-server:5201"

[[udp_egress]]
id = "iperf3-udp"
ingress_id = "iperf3-udp"
auth_key = "secret!123"
target = "test-server:5201"
