id = "siffleux-server"

[tls]
cert_pem_path = "/app/configs/siffleux/cert.pem"
key_pem_path = "/app/configs/siffleux/key.pem"

[[tcp_ingress]]
id = "siffle-tcp"
port = 9000
auth_key = "secret!123"

[[udp_ingress]]
id = "siffle-udp"
port = 9000
auth_key = "secret!123"

[[tcp_ingress]]
id = "nginx"
port = 9001
auth_key = "secret!123"

[[tcp_ingress]]
id = "iperf3-tcp"
port = 9002
auth_key = "secret!123"

[[udp_ingress]]
id = "iperf3-udp"
port = 9002
auth_key = "secret!123"

[[tcp_ingress]]
id = "echo-tcp"
port = 9003
auth_key = "secret!123"

[[udp_ingress]]
id = "echo-udp"
port = 9003
auth_key = "secret!123"
