[server]
bind_addr = "0.0.0.0:2333"

[server.transport]
type = "noise"

[server.transport.noise]
local_private_key = "cQ/vwIqNPJZmuM/OikglzBo/+jlYGrOt9i0k5h5vn1Q="

[server.services.sockperf]
token = "secret!123"
bind_addr = "0.0.0.0:9000"

[server.services.nginx]
token = "secret!123"
bind_addr = "0.0.0.0:9001"

[server.services.iperf3]
token = "secret!123"
bind_addr = "0.0.0.0:9002"

[server.services.tcp_echo]
token = "secret!123"
bind_addr = "0.0.0.0:9003"
